# Aggregate manifests used directly in the workshop.
# Each document is labeled for selective apply with -l.
# Label key: workshop=manage-operators, part=<section>

---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-file-integrity
  labels:
    workshop: manage-operators
    part: namespace-fio
    # Enable user workload monitoring of operator-managed pods
    openshift.io/cluster-monitoring: "true"
    # Loosen PSS for this operator (adjust per policy)
    pod-security.kubernetes.io/enforce: privileged

---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: file-integrity-operator
  namespace: openshift-file-integrity
  labels:
    workshop: manage-operators
    part: operatorgroup-fio
spec:
  targetNamespaces:
    - openshift-file-integrity

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: file-integrity-operator
  namespace: openshift-file-integrity
  labels:
    workshop: manage-operators
    part: subscription-fio
spec:
  channel: stable
  installPlanApproval: Manual   # Manual to demonstrate InstallPlan approval
  name: file-integrity-operator
  source: redhat-operators      # Replace if using custom/mirrored catalog
  sourceNamespace: openshift-marketplace

---
# Optional FileIntegrity CR for quick functional test
apiVersion: fileintegrity.openshift.io/v1alpha1
kind: FileIntegrity
metadata:
  name: worker-fileintegrity
  namespace: openshift-file-integrity
  labels:
    workshop: manage-operators
    part: fileintegrity-cr
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/infra
      operator: Exists
      effect: NoSchedule
  config:
    gracePeriod: 60
    maxBackups: 5

---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-compliance
  labels:
    workshop: manage-operators
    part: compliance-setup

---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: compliance-operator
  namespace: openshift-compliance
  labels:
    workshop: manage-operators
    part: compliance-setup
spec:
  targetNamespaces:
    - openshift-compliance

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: compliance-operator
  namespace: openshift-compliance
  labels:
    workshop: manage-operators
    part: compliance-setup
spec:
  channel: stable
  installPlanApproval: Automatic
  name: compliance-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace

---
# Basic ScanSettingBinding example (nist-moderate)
apiVersion: compliance.openshift.io/v1alpha1
kind: ScanSettingBinding
metadata:
  name: nist-moderate
  namespace: openshift-compliance
  labels:
    workshop: manage-operators
    part: compliance-ssb
profiles:
  - apiGroup: compliance.openshift.io/v1alpha1
    kind: Profile
    name: rhcos4-moderate
settingsRef:
  apiGroup: compliance.openshift.io/v1alpha1
  kind: ScanSetting
  name: default
