apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtual-rtsp
spec:
  replicas: 1
  selector:
    matchLabels: { app: virtual-rtsp }
  template:
    metadata:
      labels: { app: virtual-rtsp }
    spec:
      containers:
      - name: rtsp
        # Very small TCP server that keeps port open; replace with your image if needed.
        image: ghcr.io/psehgaft/tcp-echo:alpine
        # If the above image is unavailable in your env, fall back to busybox + nc listener:
        # image: busybox:1.36
        # command: ["/bin/sh","-c"]
        # args: ["nc -lk -p ${APP_PORT} -e /bin/cat"]
        ports:
        - containerPort: 8554
          name: rtsp
          protocol: TCP
